# Torch and Numpy

Details about math operation in torch can be found in: http://pytorch.org/docs/torch.html#math-operations


In [2]:
%pip install torch

   ---------------------------------------- 0.0/159.8 MB ? eta -:--:--
   ---------------------------------------- 1.6/159.8 MB 34.6 MB/s eta 0:00:05
   - -------------------------------------- 5.2/159.8 MB 66.2 MB/s eta 0:00:03
   - -------------------------------------- 7.8/159.8 MB 62.2 MB/s eta 0:00:03
   -- ------------------------------------- 11.5/159.8 MB 72.6 MB/s eta 0:00:03
   --- ----------------------------------- 16.4/159.8 MB 108.8 MB/s eta 0:00:02
   ----- --------------------------------- 20.6/159.8 MB 108.8 MB/s eta 0:00:02
   ------ -------------------------------- 25.6/159.8 MB 108.8 MB/s eta 0:00:02
   ------- ------------------------------- 29.4/159.8 MB 108.8 MB/s eta 0:00:02
   -------- ------------------------------- 32.4/159.8 MB 93.9 MB/s eta 0:00:02
   --------- ------------------------------ 36.3/159.8 MB 93.9 MB/s eta 0:00:02
   --------- ------------------------------ 38.7/159.8 MB 81.8 MB/s eta 0:00:02
   ---------- ----------------------------- 42.4/159

In [3]:
import torch
import numpy as np


In [4]:
# convert numpy to tensor or vise versa
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array:', np_data,          # [[0 1 2], [3 4 5]]
    '\ntorch tensor:', torch_data,      #  0  1  2 \n 3  4  5    [torch.LongTensor of size 2x3]
    '\ntensor to array:', tensor2array, # [[0 1 2], [3 4 5]]
)


numpy array: [[0 1 2]
 [3 4 5]] 
torch tensor: tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
tensor to array: [[0 1 2]
 [3 4 5]]


In [5]:
# abs
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  # 32-bit floating point
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor)      # [1 2 1 2]
)


abs 
numpy:  [1 2 1 2] 
torch:  tensor([1., 2., 1., 2.])


In [6]:
tensor.abs()

tensor([1., 2., 1., 2.])

In [7]:
tensor.sigmoid()

tensor([0.2689, 0.1192, 0.7311, 0.8808])

In [8]:
tensor.exp()

tensor([0.3679, 0.1353, 2.7183, 7.3891])

In [9]:
# matrix multiplication
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 32-bit floating point

print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)


matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])


Note that:

torch.dot(tensor1, tensor2) → float

Computes the dot product (inner product) of two tensors. Both tensors are treated as 1-D vectors.

In [10]:
tensor.mm(tensor)

tensor([[ 7., 10.],
        [15., 22.]])

In [11]:
tensor * tensor

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [12]:
torch.dot(torch.Tensor([2, 3]), torch.Tensor([2, 1]))

tensor(7.)